# Generated by Django 4.1.7 on 2023-03-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/profile/user.png', upload_to=''),
        ),
    ]
